# Generated by Django 4.2.4 on 2023-08-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(upload_to='D:\\Projects\\shopenv\\onlineshop\\photo/%y/%m/%d'),
        ),
    ]
